#services/containers for local testing.
services:
  postgresDB:
    image: postgres:latest

    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi

    volumes:
      - "./postgres_data:/var/lib/postgresql/data:rw"

    ports:
      - 5431:5432

    networks:
      - airflow

  pgadmin:
    image: dpage/pgadmin4
    
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    
    ports:
      - "8081:80"

    networks:
      - airflow

    volumes:
      - "./pgadmin_data:/var/lib/pgadmin:rw"

networks:
  airflow:
    name: airflow_default
    external: true
